# Generated by Django 2.2.28 on 2022-09-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200, unique=True)),
                ('cover', models.URLField(null=True)),
                ('isbn', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('published', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('pages', models.PositiveSmallIntegerField(default=None, null=True)),
                ('description', models.TextField(null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
    ]
